const GET_ALL_POLLS = 'GET_ALL_POLLS'
const GET_ONE_POLL = 'GET_ONE_POLL'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const CREATE_POLL = 'CREATE_POLL'
const DELETE_POLL = 'DELETE_POLL'
const SHOW_LOGINBAR = 'SHOW_LOGINBAR'

module.exports = {
  GET_ALL_POLLS,
  GET_ONE_POLL,
  LOGIN,
  LOGOUT,
  CREATE_POLL,
  DELETE_POLL,
  SHOW_LOGINBAR
}