const GET_ALL_POLLS = 'GET_ALL_POLLS'
const GET_ONE_POLL = 'GET_ONE_POLL'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const CREATE_POLL = 'CREATE_POLL'
const DELETE_POLL = 'DELETE_POLL'
const SHOW_LOGINBAR = 'SHOW_LOGINBAR'
const LOADING = 'LOADING'
const VOTE = 'VOTE'
const ADD_ANSWER = 'ADD_ANSWER'
const SHOW_ANSWER_FORM = 'SHOW_ANSWER_FORM'

module.exports = {
  GET_ALL_POLLS,
  GET_ONE_POLL,
  LOGIN,
  LOGOUT,
  CREATE_POLL,
  DELETE_POLL,
  SHOW_LOGINBAR,
  LOADING,
  VOTE,
  ADD_ANSWER,
  SHOW_ANSWER_FORM
}